# Generated by Django 4.2.5 on 2024-01-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
