# Generated by Django 4.2.5 on 2024-01-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_item_is_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='craeted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
